services:

  # KAFKA

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT_HOST://:9092,PLAINTEXT_DOCKER://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT_DOCKER://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: /bin/sh
    command: >
      -c "
      kafka-topics --bootstrap-server kafka:29092
      --create --if-not-exists
      --topic stats.user-actions.v1
      --partitions 1
      --replication-factor 1
      &&
      kafka-topics --bootstrap-server kafka:29092
      --create --if-not-exists
      --topic stats.events-similarity.v1
      --partitions 1
      --replication-factor 1
      "

  # STATS

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
      - POSTGRES_DB=ewm-stats
    volumes:
      - stats-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stat -d ewm-stats"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  # USER SERVICE

  user-db:
    image: postgres:16.1
    container_name: postgres-ewm-user-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=ewm-user
    volumes:
      - user-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ewm-user"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  user-service:
    build: ./core/user-service
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/ewm-user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka/
    restart: on-failure

  # REQUEST SERVICE

  request-db:
    image: postgres:16.1
    container_name: postgres-ewm-request-db
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=ewm-request
    volumes:
      - request-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ewm-request"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  request-service:
    build: ./core/request-service
    container_name: request-service
    depends_on:
      request-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/ewm-request
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka/
    restart: on-failure

  # EVENT SERVICE

  event-db:
    image: postgres:16.1
    container_name: postgres-ewm-event-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=ewm-event
    volumes:
      - event-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ewm-event"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  event-service:
    build: ./core/event-service
    container_name: event-service
    depends_on:
      event-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/ewm-event
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka/
    restart: on-failure

  # COMPILATION SERVICE

  compilation-db:
    image: postgres:16.1
    container_name: postgres-ewm-compilation-db
    ports:
      - "6546:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=ewm-compilation
    volumes:
      - compilation-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ewm-compilation"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  compilation-service:
    build: ./core/compilation-service
    container_name: compilation-service
    depends_on:
      compilation-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://compilation-db:5432/ewm-compilation
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka/
    restart: on-failure


volumes:
  stats-db-data:
  user-db-data:
  request-db-data:
  event-db-data:
  compilation-db-data: