CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS events_compilations (
    comp_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,

    PRIMARY KEY (comp_id, event_id),

    CONSTRAINT fk_events_compilations_compilation
        FOREIGN KEY (comp_id)
        REFERENCES compilations(id)
        ON DELETE CASCADE
);