server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.auto-offset-reset=earliest

analyzer.kafka.user-actions.topic=stats.user-actions.v1
analyzer.kafka.user-actions.group-id=analyzer-user-actions

analyzer.kafka.event-similarity.topic=stats.events-similarity.v1
analyzer.kafka.event-similarity.group-id=analyzer-event-similarity

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6542/ewm-stats
spring.datasource.username=stat
spring.datasource.password=stat

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always

grpc.server.port=0
