server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6546/ewm-compilation
spring.datasource.username=user
spring.datasource.password=user

grpc.client.analyzer.address=discovery:///analyzer
grpc.client.analyzer.negotiation-type=plaintext
grpc.client.analyzer.enable-keep-alive=true
grpc.client.analyzer.keep-alive-without-calls=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always