server.port=8080

spring.cloud.gateway.routes[0].id=main-service
spring.cloud.gateway.routes[0].uri=lb://main-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**,/events/**,/compilations/**,/categories/**,/admin/**