server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6544/ewm-request
spring.datasource.username=user
spring.datasource.password=user

grpc.client.collector.address=discovery:///collector
grpc.client.collector.negotiation-type=plaintext
grpc.client.collector.enable-keep-alive=true
grpc.client.collector.keep-alive-without-calls=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.cloud.openfeign.okhttp.enabled=true

spring.sql.init.mode=always