server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6544/ewm-request
spring.datasource.username=user
spring.datasource.password=user

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.cloud.openfeign.okhttp.enabled=true

spring.sql.init.mode=always