server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://stats-db:5432/ewm-stats
spring.datasource.username=stat
spring.datasource.password=stat

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always